apiVersion: v1
kind: Service
metadata:
  name: mictract-dev
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 22
    nodePort: 30022
  - name: dlv
    port: 2345
    nodePort: 32345
  - name: mictract
    port: 8080
    nodePort: 32323
  selector:
    app: mictract-dev
